### ISSUE TITLE
2.14 typos

### ISSUE THREAD

**Issue by dfailing** [katharynduffy/Environmental-Informatics-Using-Research-Infrastructures-and-their-Data#31]
Suggested Timing: Complete this exercise a few days before your NEON clumination write up
**should read**
Suggested Timing: Complete this exercise a few days before your NEON **culmination** write up

Sumarize each product with its NEON identifier, along with a sumarry.
**should read**
**Summarize** each product with its NEON identifier, along with a **summary**.

Using the NEON Ulitites package or the API pull in those data along with metadata.
**should read**
Using the NEON **Utilities** package or the API pull in those data along with metadata.

**Comment by katharynduffy** [comment]
Great, thanks!
