### ISSUE TITLE
Section 1.7 Broken Link

### ISSUE THREAD

**Issue by CameronBodine** [katharynduffy/Environmental-Informatics-Using-Research-Infrastructures-and-their-Data#5]
`Happy Git with R` navigates to Chapter 12 instead of https://happygitwithr.com/

**Comment by dfailing** [comment]
Probably intentional, since that's followed by " ... to help you link Rstudio-Git-Github ...", which is the current destination link.

**Comment by katharynduffy** [comment]
Nailed it!  That was intentional.  Thanks for the check though!

**Comment by CameronBodine** [comment]
Context ... DOH!
